### ISSUE TITLE
Подключение слайдера

### ISSUE THREAD

**Issue by kate-fsd** [RuefulMage/FD-Step4#16]
Напиши в ридми как подключить твой плагин. У тебя должна быть отдельная папка в которой конечный js и css файлы

**Comment by kate-fsd** [comment]
В этих файлах не должно быть лишнего, только сам слайдер
Сейчас, например, там есть стили для панели

**Comment by RuefulMage** [comment]
Извини, я забыл отметить номер этого issue, когда коммитил)

**Comment by kate-fsd** [comment]
Ничего страшного)
