### ISSUE TITLE
TS

### ISSUE THREAD

**Issue by Feinminen** [RuefulMage/FD-Step4#25]
Это правило достаточно полезное и практически во всех кейсах можно избежать его нарушения, тут можно просто поменять методы местами.
![image](https://user-images.githubusercontent.com/44312820/113506657-559a8d80-9570-11eb-91d3-f07cbe3faa02.png)

Мне кажется, что сейчас что-то непонятное происходит с enum-ами.

![image](https://user-images.githubusercontent.com/44312820/113506802-1c165200-9571-11eb-90dd-8d8e5c74fa2c.png)

Сначала мы получаем строку, а потом кастуем эту строку к enum-у. Непонятно зачем :)
Можно сделать просто отдельно union тип, для того чтобы выставлять конкретную ориентацию.
Если хочется использовать enum, то нужно использовать его именно как enum.

TS-овский enum дает как тип, так и настоящее значение и это значение выглядит следующим образом:
![image](https://user-images.githubusercontent.com/44312820/113506878-862ef700-9571-11eb-9fac-efe34e99df00.png)
Это не очень похоже на строку :)

Также сейчас в проекте нет описанных типов/интерфейсов, которые используются в нескольких местах, хотя это крайне удобно.

Например тип ```orientation?: Orientation, isRange?: boolean, isTipsHidden?: boolean``` используется как минимум 3 раза. И он там не один такой.

Можно просто вынести в отдельный файл описание типов и импортировать их. Т.к. это банально удобнее, а также повзоляет избежать ошибок, связанных с несовместимыми интерфейсами.
```
type SomeOptions = {
  orientation?: Orientation;
  isRange?: boolean;
  isTipsHidden?: boolean;
}
```
или
```
interface SomeOptions {
  orientation?: Orientation;
  isRange?: boolean;
  isTipsHidden?: boolean;
}
```

Хочу сразу заметить, что обычно сначала описываются required поля, а потом optional

Различий между type и interface не так много, но обычно интерфейсы описывают какой-то публичный контракт (например инстанс сайд класса), а типы описывают типы :)
Также типами можно описывать примитивные типы данных.

**Comment by RuefulMage** [comment]
Насчет no-use-before-define, Там просто хэндлеры используют друг друга( т.е. навешивают или удаляют обработчики событий), поэтому не получается расположить их так, чтобы эта ошибка не возникала
