### ISSUE TITLE
js-prefixes

### ISSUE THREAD

**Issue by Feinminen** [RuefulMage/FD-Step4#29]
По стандарту все выражения, которые используются для поиска по DOM, должны иметь префикс js-.

Сейчас классы, описанные в constants, используются для поиска, но они без префикса.

**Comment by RuefulMage** [comment]
Я заменил те классы, которые используются для поиска по DOM на классы с js- префиксом. Остальные используются для создания элемента, а потом уже к это элементу обращаются через объект.
