### ISSUE TITLE
Линтер

### ISSUE THREAD

**Issue by kate-fsd** [RuefulMage/FD-Step4#8]
Установи линтер для ts https://www.npmjs.com/package/eslint-config-airbnb-typescript и не отключай правила.
Насколько я понимаю такие ошибки возникают из за того что линтер не понимает что это ts
![image](https://user-images.githubusercontent.com/66846004/97922430-81210e00-1d6d-11eb-8617-1ffec57cebf6.png)

Поправь ошибки и форматирование. Если еще этого не сделал, установи в IDE плагин ESLint, чтобы ошибки сразу подсвечивались

**Comment by RuefulMage** [comment]
Удалил все правила кроме @typescript-eslint/no-unused-vars, так как криво работает и показывает на несуществующие ошибки

**Comment by RuefulMage** [comment]
Также в некоторых местах игнорирую правила.
1)
![image](https://user-images.githubusercontent.com/53300730/100117153-91686c80-2e85-11eb-9b63-8fdbbeb56b45.png)
 в Runner я игнорирую @typescript-eslint/no-use-before-define  потому что там по-другому не получается, т.к. два метода друг к другу обращаются.
2) no-param-reasign я игнорирую в тех местах, где изменяются свойства DOM элементов, например стили или value.
3) class-methods-use-this игнорирую там, где не получается сделать метод статическим, например, когда класс реализовывает методы интерфейса или в тестах, когда создаю мок-объекты и полностью реализовывать метод мне не нужно.
4) fsd/hof-name-prefix игнорируется так же в тестах только.
